pipeline {
        agent any
        tools {
        maven "Maven-1"
        jdk "JAva-1"
        }
        stages {
        stage('Initialize'){
        steps{
        echo "PATH = ${M2_HOME}/bin:${PATH}"
        echo "M2_HOME = /opt/maven"
        }
        }
        stage('Build') {
        steps {
        dir("/Users/ebykov/.jenkins/workspace/Selenium-Job") {
        sh 'mvn clean test'
        }
        }
        }
        }
        post {
        always {
        surefire(
        allowEmptyResults: true,
        testResults: '/Users/ebykov/IdeaProjects/ui-automation-framework/target/surefire-reports/TEST-SmokeSuite.xml'
        )
        }
        }
        }